# Generated by Django 4.2.7 on 2023-11-12 05:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pictures', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='picture',
            name='data_dict',
            field=models.JSONField(default=dict),
        ),
    ]
