# Generated by Django 4.2.7 on 2023-11-12 06:37

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('pictures', '0002_picture_data_dict'),
    ]

    operations = [
        migrations.AddField(
            model_name='picture',
            name='upload_date',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
